version: '2'
services:
  camel-mysql:
    image: mysql:8.0.19
    volumes:
      - ./mysql:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=camel_dev
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  camel-greenmail:
    image: greenmail/standalone:latest
    ports:
      - 3025:3025
      - 3110:3110
      - 3143:3143
      - 3465:3465
      - 3993:3993
      - 3995:3995
